[workspace]
resolver = "2"
members = [ "commons/zenoh-buffers", "commons/zenoh-codec", "commons/zenoh-collections", "commons/zenoh-config", "commons/zenoh-core", "commons/zenoh-crypto", "commons/zenoh-keyexpr", "commons/zenoh-macros", "commons/zenoh-protocol", "commons/zenoh-result", "commons/zenoh-shm", "commons/zenoh-sync", "commons/zenoh-task", "commons/zenoh-util", "commons/zenoh-runtime", "examples", "io/zenoh-link", "io/zenoh-link-commons", "io/zenoh-links/zenoh-link-quic/", "io/zenoh-links/zenoh-link-serial", "io/zenoh-links/zenoh-link-tcp/", "io/zenoh-links/zenoh-link-tls/", "io/zenoh-links/zenoh-link-udp/", "io/zenoh-links/zenoh-link-unixsock_stream/", "io/zenoh-links/zenoh-link-ws/", "io/zenoh-links/zenoh-link-unixpipe/", "io/zenoh-links/zenoh-link-vsock/", "io/zenoh-transport", "plugins/zenoh-backend-example", "plugins/zenoh-plugin-example", "plugins/zenoh-backend-traits", "plugins/zenoh-plugin-rest", "plugins/zenoh-plugin-storage-manager", "plugins/zenoh-plugin-trait", "zenoh", "zenoh-ext", "zenoh-ext/examples", "zenohd" ]
exclude = [ "ci/nostd-check", "ci/valgrind-check" ]

[workspace.package]
rust-version = "1.66.1"
version = "0.11.0-dev-223-g23c59329"
repository = "https://github.com/eclipse-zenoh/zenoh"
homepage = "http://zenoh.io"
authors = [ "kydos <angelo@icorsaro.net>", "Julien Enoch <julien@enoch.fr>", "Olivier HÃ©cart <olivier.hecart@zettascale.tech>", "Luca Cominardi <luca.cominardi@zettascale.tech>", "Pierre Avital <pierre.avital@zettascale.tech>" ]
edition = "2021"
license = "EPL-2.0 OR Apache-2.0"
categories = [ "network-programming" ]
description = "Zenoh: Zero Overhead Pub/sub, Store/Query and Compute."

[workspace.dependencies]
aes = "0.8.2"
ahash = "0.8.7"
async-executor = "1.5.0"
async-global-executor = "2.3.1"
async-io = "1.13.0"
async-trait = "0.1.60"
base64 = "0.21.4"
bincode = "1.3.3"
const_format = "0.2.30"
crc = "3.0.1"
criterion = "0.5"
derive_more = "0.99.17"
derive-new = "0.6.0"
tracing-loki = "0.2"
event-listener = "4.0.0"
flume = "0.11"
form_urlencoded = "1.1.0"
futures = "0.3.25"
git-version = "0.3.5"
hashbrown = "0.14"
home = "0.5.4"
http-types = "2.12.0"
humantime = "2.1.0"
json5 = "0.4.1"
keyed-set = "0.4.4"
lazy_static = "1.4.0"
libc = "0.2.139"
libloading = "0.8"
tracing = "0.1"
lz4_flex = "0.11"
num_cpus = "1.15.0"
ordered-float = "4.1.1"
panic-message = "0.3.0"
paste = "1.0.12"
petgraph = "0.6.3"
pnet = "0.34"
pnet_datalink = "0.34"
proc-macro2 = "1.0.51"
quinn = "0.10.1"
quote = "1.0.23"
rand_chacha = "0.3.1"
rcgen = "0.11"
regex = "1.7.1"
ringbuffer-spsc = "0.1.9"
rsa = "0.9"
rustc_version = "0.4.0"
rustls = "0.22.2"
rustls-native-certs = "0.7.0"
rustls-pemfile = "2.0.0"
rustls-webpki = "0.102.0"
rustls-pki-types = "1.1.0"
schemars = "0.8.12"
serde_json = "1.0.94"
serde_yaml = "0.9.19"
sha3 = "0.10.6"
shared_memory = "0.12.4"
shellexpand = "3.0.0"
stop-token = "0.7.0"
syn = "2.0"
tide = "0.16.0"
tokio-util = "0.7.10"
tokio-tungstenite = "0.21"
tokio-rustls = "0.25.0"
console-subscriber = "0.2"
typenum = "1.16.0"
unzip-n = "0.1.2"
url = "2.3.1"
urlencoding = "2.1.2"
validated_struct = "2.1.0"
vec_map = "0.8.2"
webpki-roots = "0.26.0"
z-serial = "0.2.3"

[workspace.dependencies.anyhow]
version = "1.0.69"
default-features = false

[workspace.dependencies.async-std]
version = "=1.12.0"
default-features = false

[workspace.dependencies.clap]
version = "4.4.11"
features = [ "derive" ]

[workspace.dependencies.tracing-subscriber]
version = "0.3"
features = [ "json", "env-filter" ]

[workspace.dependencies.futures-util]
version = "0.3.25"
default-features = false

[workspace.dependencies.hex]
version = "0.4.3"
default-features = false

[workspace.dependencies.hmac]
version = "0.12.1"
features = [ "std" ]

[workspace.dependencies.jsonschema]
version = "0.17.1"
default-features = false

[workspace.dependencies.nix]
version = "0.27"
features = [ "fs" ]

[workspace.dependencies.rand]
version = "0.8.5"
default-features = false

[workspace.dependencies.secrecy]
version = "0.8.0"
features = [ "serde", "alloc" ]

[workspace.dependencies.serde]
version = "1.0.154"
default-features = false
features = [ "derive" ]

[workspace.dependencies.socket2]
version = "0.5.1"
features = [ "all" ]

[workspace.dependencies.token-cell]
version = "1.4.2"
default-features = false

[workspace.dependencies.tokio]
version = "1.35.1"
default-features = false

[workspace.dependencies.uhlc]
version = "0.7.0"
default-features = false

[workspace.dependencies.uuid]
version = "1.3.0"
default-features = false
features = [ "v4" ]

[workspace.dependencies.winapi]
version = "0.3.9"
features = [ "iphlpapi" ]

[workspace.dependencies.zenoh-ext]
version = "0.11.0-dev"
path = "zenoh-ext"

[workspace.dependencies.zenoh-shm]
version = "0.11.0-dev"
path = "commons/zenoh-shm"

[workspace.dependencies.zenoh-result]
version = "0.11.0-dev"
path = "commons/zenoh-result"
default-features = false

[workspace.dependencies.zenoh-config]
version = "0.11.0-dev"
path = "commons/zenoh-config"

[workspace.dependencies.zenoh-protocol]
version = "0.11.0-dev"
path = "commons/zenoh-protocol"
default-features = false

[workspace.dependencies.zenoh-keyexpr]
version = "0.11.0-dev"
path = "commons/zenoh-keyexpr"
default-features = false

[workspace.dependencies.zenoh-core]
version = "0.11.0-dev"
path = "commons/zenoh-core"

[workspace.dependencies.zenoh-buffers]
version = "0.11.0-dev"
path = "commons/zenoh-buffers"
default-features = false

[workspace.dependencies.zenoh-util]
version = "0.11.0-dev"
path = "commons/zenoh-util"

[workspace.dependencies.zenoh-crypto]
version = "0.11.0-dev"
path = "commons/zenoh-crypto"

[workspace.dependencies.zenoh-codec]
version = "0.11.0-dev"
path = "commons/zenoh-codec"

[workspace.dependencies.zenoh-sync]
version = "0.11.0-dev"
path = "commons/zenoh-sync"

[workspace.dependencies.zenoh-collections]
version = "0.11.0-dev"
path = "commons/zenoh-collections"
default-features = false

[workspace.dependencies.zenoh-macros]
version = "0.11.0-dev"
path = "commons/zenoh-macros"

[workspace.dependencies.zenoh-plugin-trait]
version = "0.11.0-dev"
path = "plugins/zenoh-plugin-trait"
default-features = false

[workspace.dependencies.zenoh_backend_traits]
version = "0.11.0-dev"
path = "plugins/zenoh-backend-traits"

[workspace.dependencies.zenoh-transport]
version = "0.11.0-dev"
path = "io/zenoh-transport"
default-features = false

[workspace.dependencies.zenoh-link-tls]
version = "0.11.0-dev"
path = "io/zenoh-links/zenoh-link-tls"

[workspace.dependencies.zenoh-link-tcp]
version = "0.11.0-dev"
path = "io/zenoh-links/zenoh-link-tcp"

[workspace.dependencies.zenoh-link-unixsock_stream]
version = "0.11.0-dev"
path = "io/zenoh-links/zenoh-link-unixsock_stream"

[workspace.dependencies.zenoh-link-quic]
version = "0.11.0-dev"
path = "io/zenoh-links/zenoh-link-quic"

[workspace.dependencies.zenoh-link-udp]
version = "0.11.0-dev"
path = "io/zenoh-links/zenoh-link-udp"

[workspace.dependencies.zenoh-link-ws]
version = "0.11.0-dev"
path = "io/zenoh-links/zenoh-link-ws"

[workspace.dependencies.zenoh-link-unixpipe]
version = "0.11.0-dev"
path = "io/zenoh-links/zenoh-link-unixpipe"

[workspace.dependencies.zenoh-link-serial]
version = "0.11.0-dev"
path = "io/zenoh-links/zenoh-link-serial"

[workspace.dependencies.zenoh-link-vsock]
version = "0.11.0-dev"
path = "io/zenoh-links/zenoh-link-vsock"

[workspace.dependencies.zenoh-link]
version = "0.11.0-dev"
path = "io/zenoh-link"

[workspace.dependencies.zenoh-link-commons]
version = "0.11.0-dev"
path = "io/zenoh-link-commons"

[workspace.dependencies.zenoh]
version = "0.11.0-dev"
path = "zenoh"
default-features = false

[workspace.dependencies.zenoh-runtime]
version = "0.11.0-dev"
path = "commons/zenoh-runtime"

[workspace.dependencies.zenoh-task]
version = "0.11.0-dev"
path = "commons/zenoh-task"

[profile]
[profile.dev]
debug = true
opt-level = 0

[profile.fast]
inherits = "release"
opt-level = 3
debug = true
debug-assertions = true
overflow-checks = true
lto = false

[profile.release]
debug = false
lto = "fat"
codegen-units = 1
opt-level = 3
panic = "abort"